### ISSUE TITLE
Bot API 3.1

### ISSUE THREAD

**Issue by MrYadro** [go-telegram-bot-api/telegram-bot-api#107]
Build your own robotic police force for supergoups with these new methods for admin bots:

- [x] Added new methods restrictChatMember and promoteChatMember to manage users and admins, added new parameter until_date to kickChatMember for temporary bans. #105 
- [x] Added new methods exportChatInviteLink, setChatPhoto, deleteChatPhoto, setChatTitle, setChatDescription, pinChatMessage and unpinChatMessage to manage groups and channels.
- [x] Added the new fields photo, description and invite_link to the Chat object. #106 
- [x] Added the new fields until_date, can_be_edited, can_change_info, can_post_messages, can_edit_messages, can_delete_messages, can_invite_users, can_restrict_members, can_pin_messages, can_promote_members, can_send_messages, can_send_media_messages, can_send_other_messages and can_add_web_page_previews to the ChatMember object. #105

**Comment by hryamzik** [comment]
I believe there's one more thing missing in this list:

```
 update.Message.NewChatMember undefined (type *tgbotapi.Message has no field or method NewChatMember)
```

Isn't that something that should be in a changelog or readme?

**Comment by Syfaro** [comment]
@hryamzik master is potentially unstable, that's why gopkg is suggested. Once all the new features are added, everything will get tagged into a new major version. 

It was renamed into `NewChatMembers` as part of a Telegram update, it's not clear how long `NewChatMember` will even work for.

**Comment by hryamzik** [comment]
@Syfaro yep I've already fixed my code but changelog could have saved me some time. This could be a file in master branch. =)

**Comment by Syfaro** [comment]
@hryamzik it'll definitely be noted on the v5 changelog, perhaps adding a changelog somewhere wouldn't be a bad idea though.

**Comment by Lord-Protector** [comment]
@MrYadro exportChatInviteLink, pinChatMessage and unpinChatMessage are already in master.
